# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/server/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7frameworks/proto_logging/stats/enums/server/enums.proto\x12\x0e\x61ndroid.server*e\n\x12\x44\x65viceIdleModeEnum\x12\x18\n\x14\x44\x45VICE_IDLE_MODE_OFF\x10\x00\x12\x1a\n\x16\x44\x45VICE_IDLE_MODE_LIGHT\x10\x01\x12\x19\n\x15\x44\x45VICE_IDLE_MODE_DEEP\x10\x02*X\n\x0b\x45rrorSource\x12\x18\n\x14\x45RROR_SOURCE_UNKNOWN\x10\x00\x12\x0c\n\x08\x44\x41TA_APP\x10\x01\x12\x0e\n\nSYSTEM_APP\x10\x02\x12\x11\n\rSYSTEM_SERVER\x10\x03\x42\x14\x42\x10ServerProtoEnumsP\x01')

_DEVICEIDLEMODEENUM = DESCRIPTOR.enum_types_by_name['DeviceIdleModeEnum']
DeviceIdleModeEnum = enum_type_wrapper.EnumTypeWrapper(_DEVICEIDLEMODEENUM)
_ERRORSOURCE = DESCRIPTOR.enum_types_by_name['ErrorSource']
ErrorSource = enum_type_wrapper.EnumTypeWrapper(_ERRORSOURCE)
DEVICE_IDLE_MODE_OFF = 0
DEVICE_IDLE_MODE_LIGHT = 1
DEVICE_IDLE_MODE_DEEP = 2
ERROR_SOURCE_UNKNOWN = 0
DATA_APP = 1
SYSTEM_APP = 2
SYSTEM_SERVER = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\020ServerProtoEnumsP\001'
  _DEVICEIDLEMODEENUM._serialized_start=75
  _DEVICEIDLEMODEENUM._serialized_end=176
  _ERRORSOURCE._serialized_start=178
  _ERRORSOURCE._serialized_end=266
# @@protoc_insertion_point(module_scope)
