# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/intelligence/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCframeworks/proto_logging/stats/enums/stats/intelligence/enums.proto\x12\x1a\x61ndroid.stats.intelligence*E\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n\x10STATUS_SUCCEEDED\x10\x01\x12\x11\n\rSTATUS_FAILED\x10\x02*\x87\x01\n\tEventType\x12\x11\n\rEVENT_UNKNOWN\x10\x00\x12\x33\n/EVENT_CONTENT_SUGGESTIONS_CLASSIFY_CONTENT_CALL\x10\x01\x12\x32\n.EVENT_CONTENT_SUGGESTIONS_SUGGEST_CONTENT_CALL\x10\x02\x42\x18\x42\x16IntelligenceStatsEnums')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_EVENTTYPE = DESCRIPTOR.enum_types_by_name['EventType']
EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
STATUS_UNKNOWN = 0
STATUS_SUCCEEDED = 1
STATUS_FAILED = 2
EVENT_UNKNOWN = 0
EVENT_CONTENT_SUGGESTIONS_CLASSIFY_CONTENT_CALL = 1
EVENT_CONTENT_SUGGESTIONS_SUGGEST_CONTENT_CALL = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\026IntelligenceStatsEnums'
  _STATUS._serialized_start=99
  _STATUS._serialized_end=168
  _EVENTTYPE._serialized_start=171
  _EVENTTYPE._serialized_end=306
# @@protoc_insertion_point(module_scope)
