# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/devicepolicy/device_policy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKframeworks/proto_logging/stats/enums/stats/devicepolicy/device_policy.proto\x12\x1a\x61ndroid.stats.devicepolicy\"\"\n\nStringList\x12\x14\n\x0cstring_value\x18\x01 \x03(\tB\x02P\x01')



_STRINGLIST = DESCRIPTOR.message_types_by_name['StringList']
StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'frameworks.proto_logging.stats.enums.stats.devicepolicy.device_policy_pb2'
  # @@protoc_insertion_point(class_scope:android.stats.devicepolicy.StringList)
  })
_sym_db.RegisterMessage(StringList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _STRINGLIST._serialized_start=107
  _STRINGLIST._serialized_end=141
# @@protoc_insertion_point(module_scope)
