# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spatula.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rspatula.proto\"\xeb\x01\n\x13GoogleSpatulaHeader\x12;\n\x0e\x61ppCertificate\x18\x01 \x01(\x0b\x32#.GoogleSpatulaHeader.AppCertificate\x12\x1a\n\x12hashAppCertificate\x18\x02 \x01(\t\x12\x11\n\tandroidID\x18\x03 \x01(\x03\x12\x13\n\x0b\x64\x65vice_key1\x18\x04 \x01(\x03\x12\x13\n\x0b\x64\x65vice_key2\x18\x05 \x01(\t\x1a>\n\x0e\x41ppCertificate\x12\x13\n\x0bpackageName\x18\x01 \x01(\t\x12\x17\n\x0fhashPackageCert\x18\x03 \x01(\t')



_GOOGLESPATULAHEADER = DESCRIPTOR.message_types_by_name['GoogleSpatulaHeader']
_GOOGLESPATULAHEADER_APPCERTIFICATE = _GOOGLESPATULAHEADER.nested_types_by_name['AppCertificate']
GoogleSpatulaHeader = _reflection.GeneratedProtocolMessageType('GoogleSpatulaHeader', (_message.Message,), {

  'AppCertificate' : _reflection.GeneratedProtocolMessageType('AppCertificate', (_message.Message,), {
    'DESCRIPTOR' : _GOOGLESPATULAHEADER_APPCERTIFICATE,
    '__module__' : 'spatula_pb2'
    # @@protoc_insertion_point(class_scope:GoogleSpatulaHeader.AppCertificate)
    })
  ,
  'DESCRIPTOR' : _GOOGLESPATULAHEADER,
  '__module__' : 'spatula_pb2'
  # @@protoc_insertion_point(class_scope:GoogleSpatulaHeader)
  })
_sym_db.RegisterMessage(GoogleSpatulaHeader)
_sym_db.RegisterMessage(GoogleSpatulaHeader.AppCertificate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOOGLESPATULAHEADER._serialized_start=18
  _GOOGLESPATULAHEADER._serialized_end=253
  _GOOGLESPATULAHEADER_APPCERTIFICATE._serialized_start=191
  _GOOGLESPATULAHEADER_APPCERTIFICATE._serialized_end=253
# @@protoc_insertion_point(module_scope)
