# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tronfieldconfiglist.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'tronfieldconfiglist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tronfieldconfiglist.proto\"\x81\x01\n\x13TronFieldConfigList\x12=\n\x0ftronFieldConfig\x18\x01 \x03(\x0b\x32$.TronFieldConfigList.TronFieldConfig\x1a+\n\x0fTronFieldConfig\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x0b\n\x03tag\x18\x02 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tronfieldconfiglist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRONFIELDCONFIGLIST']._serialized_start=30
  _globals['_TRONFIELDCONFIGLIST']._serialized_end=159
  _globals['_TRONFIELDCONFIGLIST_TRONFIELDCONFIG']._serialized_start=116
  _globals['_TRONFIELDCONFIGLIST_TRONFIELDCONFIG']._serialized_end=159
# @@protoc_insertion_point(module_scope)
