# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/wm/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9frameworks/proto_logging/stats/enums/stats/wm/enums.proto\x12\x10\x61ndroid.stats.wm*_\n\x0bOrientation\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nROTATION_0\x10\x01\x12\x0f\n\x0bROTATION_90\x10\x02\x12\x10\n\x0cROTATION_180\x10\x03\x12\x10\n\x0cROTATION_270\x10\x04')

_ORIENTATION = DESCRIPTOR.enum_types_by_name['Orientation']
Orientation = enum_type_wrapper.EnumTypeWrapper(_ORIENTATION)
UNKNOWN = 0
ROTATION_0 = 1
ROTATION_90 = 2
ROTATION_180 = 3
ROTATION_270 = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORIENTATION._serialized_start=79
  _ORIENTATION._serialized_end=174
# @@protoc_insertion_point(module_scope)
