# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: address_form_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import postaladdress_pb2 as postaladdress__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61\x64\x64ress_form_outer_class.proto\x12\x15\x41\x64\x64ressFormOuterClass\x1a\x13postaladdress.proto\"\xdf\x02\n\x0b\x41\x64\x64ressForm\x12\x1a\n\x12\x61llowedCountryCode\x18\x04 \x03(\t\x12\x17\n\x0fphoneNumberForm\x18\x05 \x01(\x08\x12\n\n\x02id\x18\x06 \x01(\t\x12=\n\x0cinitialValue\x18\x07 \x01(\x0b\x32\'.AddressFormOuterClass.AddressFormValue\x12!\n\x19postalCodeOnlyCountryCode\x18\t \x03(\t\x12\x16\n\x0erecipientLabel\x18\n \x01(\t\x12!\n\x19hideFormFieldsToggleLabel\x18\x0b \x01(\t\x12\x15\n\rreadOnlyField\x18\x0c \x03(\x05\x12\r\n\x05title\x18\r \x01(\t\x12\x13\n\x0bhiddenField\x18\x0e \x03(\x05\x12\"\n\x1ainitialCountryI18NDataJson\x18\x0f \x01(\t\x12\x13\n\x0b\x65\x64itability\x18\x14 \x01(\x05\"I\n\x0f\x43ountrySelector\x12\x1a\n\x12\x61llowedCountryCode\x18\x02 \x03(\t\x12\x1a\n\x12initialCountryCode\x18\x03 \x01(\t\"h\n\x10\x41\x64\x64ressFormValue\x12-\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x1c.Postaladdress.PostalAddress\x12\x13\n\x0bphoneNumber\x18\x02 \x01(\t\x12\x10\n\x08isHidden\x18\x03 \x01(\x08\x42^\nEcom.google.commerce.payments.orchestration.proto.ui.common.componentsB\x15\x41\x64\x64ressFormOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_form_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nEcom.google.commerce.payments.orchestration.proto.ui.common.componentsB\025AddressFormOuterClass'
  _globals['_ADDRESSFORM']._serialized_start=79
  _globals['_ADDRESSFORM']._serialized_end=430
  _globals['_COUNTRYSELECTOR']._serialized_start=432
  _globals['_COUNTRYSELECTOR']._serialized_end=505
  _globals['_ADDRESSFORMVALUE']._serialized_start=507
  _globals['_ADDRESSFORMVALUE']._serialized_end=611
# @@protoc_insertion_point(module_scope)
