# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: billing_profile_protos.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import common_device_pb2 as common__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x62illing_profile_protos.proto\x12\x14\x42illingProfileProtos\x1a\x0c\x63ommon.proto\x1a\x13\x63ommon_device.proto\"\x84\x02\n\x0e\x42illingProfile\x12,\n\ninstrument\x18\x01 \x03(\x0b\x32\x18.CommonDevice.Instrument\x12$\n\x1cselectedExternalInstrumentId\x18\x02 \x01(\t\x12H\n\x14\x62illingProfileOption\x18\x03 \x03(\x0b\x32*.BillingProfileProtos.BillingProfileOption\x12%\n\x1dpaymentsIntegratorCommonToken\x18\x06 \x01(\x0c\x12-\n\x16remindMeLaterIconImage\x18\x07 \x01(\x0b\x32\r.Common.Image\"\x8f\x03\n\x14\x42illingProfileOption\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x14\n\x0c\x64isplayTitle\x18\x02 \x01(\t\x12\x1c\n\x14\x65xternalInstrumentId\x18\x03 \x01(\t\x12*\n\ttopupInfo\x18\x04 \x01(\x0b\x32\x17.CommonDevice.TopupInfo\x12T\n\x1e\x63\x61rrierBillingInstrumentStatus\x18\x05 \x01(\x0b\x32,.CommonDevice.CarrierBillingInstrumentStatus\x12:\n\x11genericInstrument\x18\x06 \x01(\x0b\x32\x1f.CommonDevice.GenericInstrument\x12)\n!paymentsIntegratorInstrumentToken\x18\x07 \x01(\x0c\x12 \n\ticonImage\x18\x08 \x01(\x0b\x32\r.Common.Image\x12\x18\n\x10serverLogsCookie\x18\t \x01(\x0c\x12\x10\n\x08typeName\x18\n \x01(\tB8\n com.google.android.finsky.protosB\x14\x42illingProfileProtos')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'billing_profile_protos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\024BillingProfileProtos'
  _globals['_BILLINGPROFILE']._serialized_start=90
  _globals['_BILLINGPROFILE']._serialized_end=350
  _globals['_BILLINGPROFILEOPTION']._serialized_start=353
  _globals['_BILLINGPROFILEOPTION']._serialized_end=752
# @@protoc_insertion_point(module_scope)
