# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: browse.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resolve_link_pb2 as resolve__link__pb2
import play_survey_pb2 as play__survey__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62rowse.proto\x12\x06\x42rowse\x1a\x12resolve_link.proto\x1a\x11play_survey.proto\x1a\x0c\x63ommon.proto\"\xba\x01\n\tQuickLink\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x05image\x18\x02 \x01(\x0b\x32\r.Common.Image\x12\'\n\x04link\x18\x03 \x01(\x0b\x32\x19.ResolveLink.ResolvedLink\x12\x17\n\x0f\x64isplayRequired\x18\x04 \x01(\x08\x12\x18\n\x10serverLogsCookie\x18\x05 \x01(\x0c\x12\x11\n\tbackendId\x18\x06 \x01(\x05\x12\x12\n\nprismStyle\x18\x07 \x01(\x08\"\x88\x03\n\x0e\x42rowseResponse\x12\x13\n\x0b\x63ontentsUrl\x18\x01 \x01(\t\x12\x10\n\x08promoUrl\x18\x02 \x01(\t\x12$\n\x08\x63\x61tegory\x18\x03 \x03(\x0b\x32\x12.Browse.BrowseLink\x12&\n\nbreadcrumb\x18\x04 \x03(\x0b\x32\x12.Browse.BrowseLink\x12$\n\tquickLink\x18\x05 \x03(\x0b\x32\x11.Browse.QuickLink\x12\x18\n\x10serverLogsCookie\x18\x06 \x01(\x0c\x12\r\n\x05title\x18\x07 \x01(\t\x12\x11\n\tbackendId\x18\x08 \x01(\x05\x12$\n\tbrowseTab\x18\t \x03(\x0b\x32\x11.Browse.BrowseTab\x12\x17\n\x0flandingTabIndex\x18\n \x01(\x05\x12\x19\n\x11quickLinkTabIndex\x18\x0b \x01(\x05\x12!\n\x19quickLinkFallbackTabIndex\x18\x0c \x01(\x05\x12\"\n\x06survey\x18\r \x01(\x0b\x32\x12.PlaySurvey.Survey\"k\n\tBrowseTab\x12\r\n\x05title\x18\x01 \x01(\t\x12\x18\n\x10serverLogsCookie\x18\x02 \x01(\x0c\x12\x0f\n\x07listUrl\x18\x03 \x01(\t\x12$\n\x08\x63\x61tegory\x18\x04 \x03(\x0b\x32\x12.Browse.BrowseLink\"E\n\nBrowseLink\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taUrl\x18\x03 \x01(\t\x12\x18\n\x10serverLogsCookie\x18\x04 \x01(\x0c\x42*\n com.google.android.finsky.protosB\x06\x42rowse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'browse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\006Browse'
  _globals['_QUICKLINK']._serialized_start=78
  _globals['_QUICKLINK']._serialized_end=264
  _globals['_BROWSERESPONSE']._serialized_start=267
  _globals['_BROWSERESPONSE']._serialized_end=659
  _globals['_BROWSETAB']._serialized_start=661
  _globals['_BROWSETAB']._serialized_end=768
  _globals['_BROWSELINK']._serialized_start=770
  _globals['_BROWSELINK']._serialized_end=839
# @@protoc_insertion_point(module_scope)
