# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: challenge_action.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import challenge_proto_pb2 as challenge__proto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63hallenge_action.proto\x12\x0f\x43hallengeAction\x1a\x15\x63hallenge_proto.proto\"Z\n\x11\x43hallengeResponse\x12,\n\tchallenge\x18\x01 \x01(\x0b\x32\x19.ChallengeProto.Challenge\x12\x17\n\x0f\x63hallengePassed\x18\x02 \x01(\x08\x42\x33\n com.google.android.finsky.protosB\x0f\x43hallengeAction')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'challenge_action_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\017ChallengeAction'
  _globals['_CHALLENGERESPONSE']._serialized_start=66
  _globals['_CHALLENGERESPONSE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
