# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_form_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import legal_message_set_outer_class_pb2 as legal__message__set__outer__class__pb2
import tax_info_form_outer_class_pb2 as tax__info__form__outer__class__pb2
import address_form_outer_class_pb2 as address__form__outer__class__pb2
import instrument_form_outer_class_pb2 as instrument__form__outer__class__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ustomer_form_outer_class.proto\x12\x16\x43ustomerFormOuterClass\x1a#legal_message_set_outer_class.proto\x1a\x1ftax_info_form_outer_class.proto\x1a\x1e\x61\x64\x64ress_form_outer_class.proto\x1a!instrument_form_outer_class.proto\"\xff\x01\n\x11\x43ustomerFormValue\x12\x41\n\ninstrument\x18\x01 \x01(\x0b\x32-.InstrumentFormOuterClass.InstrumentFormValue\x12\x14\n\x0clegalDocData\x18\x03 \x01(\t\x12=\n\x0clegalAddress\x18\x04 \x01(\x0b\x32\'.AddressFormOuterClass.AddressFormValue\x12\x18\n\x10legalCountryCode\x18\x05 \x01(\t\x12\x38\n\x07taxInfo\x18\x06 \x01(\x0b\x32\'.TaxInfoFormOuterClass.TaxInfoFormValue\"\xf8\x02\n\x0c\x43ustomerForm\x12<\n\x10legalAddressForm\x18\x01 \x01(\x0b\x32\".AddressFormOuterClass.AddressForm\x12@\n\x0einstrumentForm\x18\x02 \x01(\x0b\x32(.InstrumentFormOuterClass.InstrumentForm\x12\x41\n\rlegalMessages\x18\x04 \x01(\x0b\x32*.LegalMessageSetOuterClass.LegalMessageSet\x12\n\n\x02id\x18\x05 \x01(\t\x12\x44\n\x14legalCountrySelector\x18\x06 \x01(\x0b\x32&.AddressFormOuterClass.CountrySelector\x12\x37\n\x0btaxInfoForm\x18\x07 \x03(\x0b\x32\".TaxInfoFormOuterClass.TaxInfoForm\x12\x1a\n\x12initialTaxInfoForm\x18\x08 \x01(\x05\x42h\nNcom.google.commerce.payments.orchestration.proto.ui.common.components.customerB\x16\x43ustomerFormOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_form_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nNcom.google.commerce.payments.orchestration.proto.ui.common.components.customerB\026CustomerFormOuterClass'
  _globals['_CUSTOMERFORMVALUE']._serialized_start=197
  _globals['_CUSTOMERFORMVALUE']._serialized_end=452
  _globals['_CUSTOMERFORM']._serialized_start=455
  _globals['_CUSTOMERFORM']._serialized_end=831
# @@protoc_insertion_point(module_scope)
