# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dcb.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import legal_message_outer_class_pb2 as legal__message__outer__class__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdcb.proto\x12\x03\x44\x63\x62\x1a\x1flegal_message_outer_class.proto\"\x85\x01\n\x18\x44\x63\x62VerifyAssociationForm\x12\x16\n\x0esmsPhoneNumber\x18\x01 \x01(\t\x12\x12\n\nsmsMessage\x18\x02 \x01(\t\x12=\n\x0frequiredMessage\x18\x03 \x01(\x0b\x32$.LegalMessageOuterClass.LegalMessage\"5\n\x1d\x44\x63\x62VerifyAssociationFormValue\x12\x14\n\x0clegalDocData\x18\x01 \x01(\tB]\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\x03\x44\x63\x62')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dcb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nVcom.google.commerce.payments.orchestration.proto.ui.common.components.instrument.typesB\003Dcb'
  _globals['_DCBVERIFYASSOCIATIONFORM']._serialized_start=52
  _globals['_DCBVERIFYASSOCIATIONFORM']._serialized_end=185
  _globals['_DCBVERIFYASSOCIATIONFORMVALUE']._serialized_start=187
  _globals['_DCBVERIFYASSOCIATIONFORMVALUE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
