# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_info_proto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x65\x62ug_info_proto.proto\x12\x0e\x44\x65\x62ugInfoProto\"x\n\tDebugInfo\x12\x0f\n\x07message\x18\x01 \x03(\t\x12\x30\n\x06timing\x18\x02 \x03(\x0b\x32 .DebugInfoProto.DebugInfo.Timing\x1a(\n\x06Timing\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08timeInMs\x18\x04 \x01(\x01\x42\x32\n com.google.android.finsky.protosB\x0e\x44\x65\x62ugInfoProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_info_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\016DebugInfoProto'
  _globals['_DEBUGINFO']._serialized_start=42
  _globals['_DEBUGINFO']._serialized_end=162
  _globals['_DEBUGINFO_TIMING']._serialized_start=122
  _globals['_DEBUGINFO_TIMING']._serialized_end=162
# @@protoc_insertion_point(module_scope)
