# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug_settings.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65\x62ug_settings.proto\x12\rDebugSettings\"R\n\x15\x44\x65\x62ugSettingsResponse\x12\x1b\n\x13playCountryOverride\x18\x01 \x01(\t\x12\x1c\n\x14playCountryDebugInfo\x18\x02 \x01(\tB1\n com.google.android.finsky.protosB\rDebugSettings')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\rDebugSettings'
  _globals['_DEBUGSETTINGSRESPONSE']._serialized_start=39
  _globals['_DEBUGSETTINGSRESPONSE']._serialized_end=121
# @@protoc_insertion_point(module_scope)
