# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delivery.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import android_app_delivery_pb2 as android__app__delivery__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65livery.proto\x12\x08\x44\x65livery\x1a\x1a\x61ndroid_app_delivery.proto\"g\n\x10\x44\x65liveryResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x43\n\x0f\x61ppDeliveryData\x18\x02 \x01(\x0b\x32*.AndroidAppDelivery.AndroidAppDeliveryDataB,\n com.google.android.finsky.protosB\x08\x44\x65livery')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\010Delivery'
  _globals['_DELIVERYRESPONSE']._serialized_start=56
  _globals['_DELIVERYRESPONSE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
