# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc_annotations.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resolve_link_pb2 as resolve__link__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64oc_annotations.proto\x12\x0e\x44ocAnnotations\x1a\x12resolve_link.proto\x1a\x0c\x63ommon.proto\"\x8a\x01\n\x16PurchaseHistoryDetails\x12\x1d\n\x15purchaseTimestampMsec\x18\x02 \x01(\x03\x12\x1b\n\x13purchaseDetailsHtml\x18\x03 \x01(\t\x12\x1c\n\x05offer\x18\x05 \x01(\x0b\x32\r.Common.Offer\x12\x16\n\x0epurchaseStatus\x18\x06 \x01(\t\"\xa3\x01\n\x05\x42\x61\x64ge\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1c\n\x05image\x18\x02 \x03(\x0b\x32\r.Common.Image\x12\x11\n\tbrowseUrl\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1a\n\x12textInTitleSection\x18\x05 \x01(\t\x12)\n\x12\x65xpandedBadgeImage\x18\x06 \x01(\x0b\x32\r.Common.Image\"^\n\x0fSectionMetadata\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0f\n\x07listUrl\x18\x02 \x01(\t\x12\x11\n\tbrowseUrl\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65scriptionHtml\x18\x04 \x01(\t\"y\n\x0bPromotedDoc\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08subtitle\x18\x02 \x01(\t\x12\x1c\n\x05image\x18\x03 \x03(\x0b\x32\r.Common.Image\x12\x17\n\x0f\x64\x65scriptionHtml\x18\x04 \x01(\t\x12\x12\n\ndetailsUrl\x18\x05 \x01(\t\"X\n\x04Link\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12/\n\x0cresolvedLink\x18\x02 \x01(\x0b\x32\x19.ResolveLink.ResolvedLink\x12\x12\n\nuriBackend\x18\x03 \x01(\x05\"#\n\x07Warning\x12\x18\n\x10localizedMessage\x18\x01 \x01(\t\"c\n\x0e\x42\x61\x64geContainer\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1c\n\x05image\x18\x02 \x03(\x0b\x32\r.Common.Image\x12$\n\x05\x62\x61\x64ge\x18\x03 \x03(\x0b\x32\x15.DocAnnotations.BadgeB2\n com.google.android.finsky.protosB\x0e\x44ocAnnotations')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doc_annotations_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\016DocAnnotations'
  _globals['_PURCHASEHISTORYDETAILS']._serialized_start=76
  _globals['_PURCHASEHISTORYDETAILS']._serialized_end=214
  _globals['_BADGE']._serialized_start=217
  _globals['_BADGE']._serialized_end=380
  _globals['_SECTIONMETADATA']._serialized_start=382
  _globals['_SECTIONMETADATA']._serialized_end=476
  _globals['_PROMOTEDDOC']._serialized_start=478
  _globals['_PROMOTEDDOC']._serialized_end=599
  _globals['_LINK']._serialized_start=601
  _globals['_LINK']._serialized_end=689
  _globals['_WARNING']._serialized_start=691
  _globals['_WARNING']._serialized_end=726
  _globals['_BADGECONTAINER']._serialized_start=728
  _globals['_BADGECONTAINER']._serialized_end=827
# @@protoc_insertion_point(module_scope)
