# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doc_list.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_v2_pb2 as document__v2__pb2
import document_v1_pb2 as document__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64oc_list.proto\x12\x07\x44ocList\x1a\x11\x64ocument_v2.proto\x1a\x11\x64ocument_v1.proto\"O\n\x0cListResponse\x12\x1f\n\x06\x62ucket\x18\x01 \x03(\x0b\x32\x0f.DocList.Bucket\x12\x1e\n\x03\x64oc\x18\x02 \x03(\x0b\x32\x11.DocumentV2.DocV2\"\x84\x02\n\x06\x42ucket\x12#\n\x08\x64ocument\x18\x01 \x03(\x0b\x32\x11.DocumentV1.DocV1\x12\x13\n\x0bmultiCorpus\x18\x02 \x01(\x08\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07iconUrl\x18\x04 \x01(\t\x12\x17\n\x0f\x66ullContentsUrl\x18\x05 \x01(\t\x12\x11\n\trelevance\x18\x06 \x01(\x01\x12\x18\n\x10\x65stimatedResults\x18\x07 \x01(\x03\x12\x17\n\x0f\x61nalyticsCookie\x18\x08 \x01(\t\x12\x1b\n\x13\x66ullContentsListUrl\x18\t \x01(\t\x12\x13\n\x0bnextPageUrl\x18\n \x01(\t\x12\x0f\n\x07ordered\x18\x0b \x01(\x08\x42+\n com.google.android.finsky.protosB\x07\x44ocList')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doc_list_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\007DocList'
  _globals['_LISTRESPONSE']._serialized_start=65
  _globals['_LISTRESPONSE']._serialized_end=144
  _globals['_BUCKET']._serialized_start=147
  _globals['_BUCKET']._serialized_end=407
# @@protoc_insertion_point(module_scope)
