# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: form_header_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66orm_header_outer_class.proto\x12\x14\x46ormHeaderOuterClass\":\n\nFormHeader\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdataToken\x18\x02 \x01(\x0c\x12\r\n\x05title\x18\x04 \x01(\tB]\nEcom.google.commerce.payments.orchestration.proto.ui.common.componentsB\x14\x46ormHeaderOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'form_header_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nEcom.google.commerce.payments.orchestration.proto.ui.common.componentsB\024FormHeaderOuterClass'
  _globals['_FORMHEADER']._serialized_start=55
  _globals['_FORMHEADER']._serialized_end=113
# @@protoc_insertion_point(module_scope)
