# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_form_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import simple_form_outer_class_pb2 as simple__form__outer__class__pb2
import credit_card_pb2 as credit__card__pb2
import dcb_pb2 as dcb__pb2
import username_password_pb2 as username__password__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!instrument_form_outer_class.proto\x12\x18InstrumentFormOuterClass\x1a\x1dsimple_form_outer_class.proto\x1a\x11\x63redit_card.proto\x1a\tdcb.proto\x1a\x17username_password.proto\"\x8e\x02\n\x13InstrumentFormValue\x12\x33\n\ncreditCard\x18\x01 \x01(\x0b\x32\x1f.CreditCard.CreditCardFormValue\x12@\n\x14\x64\x63\x62VerifyAssociation\x18\x04 \x01(\x0b\x32\".Dcb.DcbVerifyAssociationFormValue\x12\x45\n\x10usernamePassword\x18\x06 \x01(\x0b\x32+.UsernamePassword.UsernamePasswordFormValue\x12\x39\n\nsimpleForm\x18\x0b \x01(\x0b\x32%.SimpleFormOuterClass.SimpleFormValue\"\xf5\x01\n\x0eInstrumentForm\x12.\n\ncreditCard\x18\x02 \x01(\x0b\x32\x1a.CreditCard.CreditCardForm\x12;\n\x14\x64\x63\x62VerifyAssociation\x18\x05 \x01(\x0b\x32\x1d.Dcb.DcbVerifyAssociationForm\x12@\n\x10usernamePassword\x18\x07 \x01(\x0b\x32&.UsernamePassword.UsernamePasswordForm\x12\x34\n\nsimpleForm\x18\x0b \x01(\x0b\x32 .SimpleFormOuterClass.SimpleFormBl\nPcom.google.commerce.payments.orchestration.proto.ui.common.components.instrumentB\x18InstrumentFormOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_form_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nPcom.google.commerce.payments.orchestration.proto.ui.common.components.instrumentB\030InstrumentFormOuterClass'
  _globals['_INSTRUMENTFORMVALUE']._serialized_start=150
  _globals['_INSTRUMENTFORMVALUE']._serialized_end=420
  _globals['_INSTRUMENTFORM']._serialized_start=423
  _globals['_INSTRUMENTFORM']._serialized_end=668
# @@protoc_insertion_point(module_scope)
