# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_setup_info_proto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import challenge_proto_pb2 as challenge__proto__pb2
import common_device_pb2 as common__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!instrument_setup_info_proto.proto\x12\x18InstrumentSetupInfoProto\x1a\x15\x63hallenge_proto.proto\x1a\x13\x63ommon_device.proto\"\xb8\x01\n\x13InstrumentSetupInfo\x12\x18\n\x10instrumentFamily\x18\x01 \x01(\x05\x12\x11\n\tsupported\x18\x02 \x01(\x08\x12:\n\x10\x61\x64\x64ressChallenge\x18\x03 \x01(\x0b\x32 .ChallengeProto.AddressChallenge\x12$\n\x07\x62\x61lance\x18\x04 \x01(\x0b\x32\x13.CommonDevice.Money\x12\x12\n\nfooterHtml\x18\x05 \x03(\tB<\n com.google.android.finsky.protosB\x18InstrumentSetupInfoProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_setup_info_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\030InstrumentSetupInfoProto'
  _globals['_INSTRUMENTSETUPINFO']._serialized_start=108
  _globals['_INSTRUMENTSETUPINFO']._serialized_end=292
# @@protoc_insertion_point(module_scope)
