# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library_update_proto.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1alibrary_update_proto.proto\x12\x12LibraryUpdateProto\x1a\x0c\x63ommon.proto\"D\n\x13LibraryInAppDetails\x12\x1a\n\x12signedPurchaseData\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\t\"\xce\x01\n\x1aLibrarySubscriptionDetails\x12\x1f\n\x17initiationTimestampMsec\x18\x01 \x01(\x03\x12)\n!deprecatedValidUntilTimestampMsec\x18\x02 \x01(\x03\x12\x14\n\x0c\x61utoRenewing\x18\x03 \x01(\x08\x12\x1f\n\x17trialUntilTimestampMsec\x18\x04 \x01(\x03\x12\x1a\n\x12signedPurchaseData\x18\x05 \x01(\t\x12\x11\n\tsignature\x18\x06 \x01(\t\"\xe5\x02\n\x0fLibraryMutation\x12\x1c\n\x05\x64ocid\x18\x01 \x01(\x0b\x32\r.Common.Docid\x12\x11\n\tofferType\x18\x02 \x01(\x05\x12\x14\n\x0c\x64ocumentHash\x18\x03 \x01(\x03\x12\x0f\n\x07\x64\x65leted\x18\x04 \x01(\x08\x12\x39\n\nappDetails\x18\x05 \x01(\x0b\x32%.LibraryUpdateProto.LibraryAppDetails\x12K\n\x13subscriptionDetails\x18\x06 \x01(\x0b\x32..LibraryUpdateProto.LibrarySubscriptionDetails\x12=\n\x0cinAppDetails\x18\x07 \x01(\x0b\x32\'.LibraryUpdateProto.LibraryInAppDetails\x12\x1f\n\x17validUntilTimestampMsec\x18\x08 \x01(\x03\x12\x12\n\npreordered\x18\t \x01(\x08\"\x9f\x01\n\rLibraryUpdate\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0e\n\x06\x63orpus\x18\x02 \x01(\x05\x12\x13\n\x0bserverToken\x18\x03 \x01(\x0c\x12\x35\n\x08mutation\x18\x04 \x03(\x0b\x32#.LibraryUpdateProto.LibraryMutation\x12\x0f\n\x07hasMore\x18\x05 \x01(\x08\x12\x11\n\tlibraryId\x18\x06 \x01(\t\"v\n\x11LibraryAppDetails\x12\x17\n\x0f\x63\x65rtificateHash\x18\x02 \x03(\t\x12\"\n\x1arefundTimeoutTimestampMsec\x18\x03 \x01(\x03\x12$\n\x1cpostDeliveryRefundWindowMsec\x18\x04 \x01(\x03\"v\n\x12\x43lientLibraryState\x12\x0e\n\x06\x63orpus\x18\x01 \x01(\x05\x12\x13\n\x0bserverToken\x18\x02 \x01(\x0c\x12\x13\n\x0bhashCodeSum\x18\x03 \x01(\x03\x12\x13\n\x0blibrarySize\x18\x04 \x01(\x05\x12\x11\n\tlibraryId\x18\x05 \x01(\tB6\n com.google.android.finsky.protosB\x12LibraryUpdateProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_update_proto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\022LibraryUpdateProto'
  _globals['_LIBRARYINAPPDETAILS']._serialized_start=64
  _globals['_LIBRARYINAPPDETAILS']._serialized_end=132
  _globals['_LIBRARYSUBSCRIPTIONDETAILS']._serialized_start=135
  _globals['_LIBRARYSUBSCRIPTIONDETAILS']._serialized_end=341
  _globals['_LIBRARYMUTATION']._serialized_start=344
  _globals['_LIBRARYMUTATION']._serialized_end=701
  _globals['_LIBRARYUPDATE']._serialized_start=704
  _globals['_LIBRARYUPDATE']._serialized_end=863
  _globals['_LIBRARYAPPDETAILS']._serialized_start=865
  _globals['_LIBRARYAPPDETAILS']._serialized_end=983
  _globals['_CLIENTLIBRARYSTATE']._serialized_start=985
  _globals['_CLIENTLIBRARYSTATE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
