# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x12\x03Log\"4\n\nLogRequest\x12&\n\nclickEvent\x18\x01 \x03(\x0b\x32\x12.Log.ClickLogEvent\"\r\n\x0bLogResponse\"l\n\rClickLogEvent\x12\x11\n\teventTime\x18\x01 \x01(\x03\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06listId\x18\x03 \x01(\t\x12\x13\n\x0breferrerUrl\x18\x04 \x01(\t\x12\x16\n\x0ereferrerListId\x18\x05 \x01(\tB\'\n com.google.android.finsky.protosB\x03Log')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\003Log'
  _globals['_LOGREQUEST']._serialized_start=18
  _globals['_LOGREQUEST']._serialized_end=70
  _globals['_LOGRESPONSE']._serialized_start=72
  _globals['_LOGRESPONSE']._serialized_end=85
  _globals['_CLICKLOGEVENT']._serialized_start=87
  _globals['_CLICKLOGEVENT']._serialized_end=195
# @@protoc_insertion_point(module_scope)
