# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modify_library.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import library_update_proto_pb2 as library__update__proto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14modify_library.proto\x12\rModifyLibrary\x1a\x1alibrary_update_proto.proto\"Q\n\x15ModifyLibraryResponse\x12\x38\n\rlibraryUpdate\x18\x01 \x01(\x0b\x32!.LibraryUpdateProto.LibraryUpdate\"p\n\x14ModifyLibraryRequest\x12\x11\n\tlibraryId\x18\x01 \x01(\t\x12\x13\n\x0b\x66orAddDocid\x18\x02 \x03(\t\x12\x17\n\x0f\x66orRemovalDocid\x18\x03 \x03(\t\x12\x17\n\x0f\x66orArchiveDocid\x18\x04 \x03(\tB1\n com.google.android.finsky.protosB\rModifyLibrary')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modify_library_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\rModifyLibrary'
  _globals['_MODIFYLIBRARYRESPONSE']._serialized_start=67
  _globals['_MODIFYLIBRARYRESPONSE']._serialized_end=148
  _globals['_MODIFYLIBRARYREQUEST']._serialized_start=150
  _globals['_MODIFYLIBRARYREQUEST']._serialized_end=262
# @@protoc_insertion_point(module_scope)
