# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_survey.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11play_survey.proto\x12\nPlaySurvey\x1a\x0c\x63ommon.proto\"Z\n\rSurveyContent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12(\n\x06\x61nswer\x18\x03 \x03(\x0b\x32\x18.PlaySurvey.SurveyAnswer\"d\n\x06Survey\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x06prompt\x18\x02 \x01(\x0b\x32\x12.PlaySurvey.Prompt\x12*\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x19.PlaySurvey.SurveyContent\"P\n\x06Prompt\x12\x12\n\npromptText\x18\x01 \x01(\t\x12\x18\n\x10\x61\x63\x63\x65ptButtonText\x18\x02 \x01(\t\x12\x18\n\x10rejectButtonText\x18\x03 \x01(\t\"L\n\x0cSurveyAnswer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1b\n\x04icon\x18\x02 \x01(\x0b\x32\r.Common.Image\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tB.\n com.google.android.finsky.protosB\nPlaySurvey')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'play_survey_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\nPlaySurvey'
  _globals['_SURVEYCONTENT']._serialized_start=47
  _globals['_SURVEYCONTENT']._serialized_end=137
  _globals['_SURVEY']._serialized_start=139
  _globals['_SURVEY']._serialized_end=239
  _globals['_PROMPT']._serialized_start=241
  _globals['_PROMPT']._serialized_end=321
  _globals['_SURVEYANSWER']._serialized_start=323
  _globals['_SURVEYANSWER']._serialized_end=399
# @@protoc_insertion_point(module_scope)
