# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_plus_profile.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_pb2 as document__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17play_plus_profile.proto\x12\x0fPlayPlusProfile\x1a\x0e\x64ocument.proto\"[\n\x17PlayPlusProfileResponse\x12+\n\x0buserProfile\x18\x01 \x01(\x0b\x32\x16.Document.PlayDocument\x12\x13\n\x0bisGplusUser\x18\x02 \x01(\x08\x42\x33\n com.google.android.finsky.protosB\x0fPlayPlusProfile')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'play_plus_profile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\017PlayPlusProfile'
  _globals['_PLAYPLUSPROFILERESPONSE']._serialized_start=60
  _globals['_PLAYPLUSPROFILERESPONSE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
