# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: play_response.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import plus_profile_pb2 as plus__profile__pb2
import response_messages_pb2 as response__messages__pb2
import play_plus_profile_pb2 as play__plus__profile__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13play_response.proto\x12\x0cPlayResponse\x1a\x12plus_profile.proto\x1a\x17response_messages.proto\x1a\x17play_plus_profile.proto\"\x9b\x01\n\x0bPlayPayload\x12M\n\x1boBSOLETEPlusProfileResponse\x18\x01 \x01(\x0b\x32(.PlayPlusProfile.PlayPlusProfileResponse\x12=\n\x13plusProfileResponse\x18\x02 \x01(\x0b\x32 .PlusProfile.PlusProfileResponse\"\xdd\x01\n\x13PlayResponseWrapper\x12*\n\x07payload\x18\x01 \x01(\x0b\x32\x19.PlayResponse.PlayPayload\x12\x32\n\x08\x63ommands\x18\x02 \x01(\x0b\x32 .ResponseMessages.ServerCommands\x12,\n\x08preFetch\x18\x03 \x03(\x0b\x32\x1a.ResponseMessages.PreFetch\x12\x38\n\x0eserverMetadata\x18\x04 \x01(\x0b\x32 .ResponseMessages.ServerMetadataB0\n com.google.android.finsky.protosB\x0cPlayResponse')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'play_response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\014PlayResponse'
  _globals['_PLAYPAYLOAD']._serialized_start=108
  _globals['_PLAYPAYLOAD']._serialized_end=263
  _globals['_PLAYRESPONSEWRAPPER']._serialized_start=266
  _globals['_PLAYRESPONSEWRAPPER']._serialized_end=487
# @@protoc_insertion_point(module_scope)
