# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postaladdress.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13postaladdress.proto\x12\rPostaladdress\"\x8f\x04\n\rPostalAddress\x12\x17\n\x0f\x63ountryNameCode\x18\x01 \x01(\t\x12\x13\n\x0b\x63ountryName\x18\x02 \x01(\t\x12\x1e\n\x16\x61\x64ministrativeAreaName\x18\x03 \x01(\t\x12!\n\x19subAdministrativeAreaName\x18\x04 \x01(\t\x12\x14\n\x0clocalityName\x18\x05 \x01(\t\x12\x18\n\x10thoroughfareName\x18\x06 \x01(\t\x12\x1a\n\x12thoroughfareNumber\x18\x0b \x01(\t\x12\x18\n\x10postalCodeNumber\x18\x0c \x01(\t\x12!\n\x19postalCodeNumberExtension\x18\r \x01(\t\x12\x13\n\x0b\x61\x64\x64ressLine\x18\x0e \x03(\t\x12\x13\n\x0bpremiseName\x18\x0f \x01(\t\x12\x16\n\x0esubPremiseName\x18\x10 \x01(\t\x12\x1d\n\x15\x64\x65pendentLocalityName\x18\x11 \x01(\t\x12!\n\x19\x64\x65pendentThoroughfareName\x18\x15 \x01(\t\x12\x14\n\x0clanguageCode\x18\x1a \x01(\t\x12\x10\n\x08\x66irmName\x18\x1b \x01(\t\x12\x15\n\rrecipientName\x18\x1c \x01(\t\x12\x13\n\x0bsortingCode\x18\x1d \x01(\t\x12\x15\n\rpostBoxNumber\x18\x1e \x01(\t\x12\x15\n\x0c\x65mailAddress\x18\xfe\x08 \x01(\tB,\n\x1b\x63om.google.location.countryB\rPostaladdress')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postaladdress_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.google.location.countryB\rPostaladdress'
  _globals['_POSTALADDRESS']._serialized_start=39
  _globals['_POSTALADDRESS']._serialized_end=566
# @@protoc_insertion_point(module_scope)
