# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rate_suggested_content_response.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%rate_suggested_content_response.proto\x12\x1cRateSuggestedContentResponse\"\x1e\n\x1cRateSuggestedContentResponseBB\n com.google.android.finsky.protosB\x1cRateSuggestedContentResponseP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rate_suggested_content_response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\034RateSuggestedContentResponseP\001'
  _globals['_RATESUGGESTEDCONTENTRESPONSE']._serialized_start=71
  _globals['_RATESUGGESTEDCONTENTRESPONSE']._serialized_end=101
# @@protoc_insertion_point(module_scope)
