# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_context_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import context_outer_class_pb2 as context__outer__class__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!request_context_outer_class.proto\x12\x18RequestContextOuterClass\x1a\x19\x63ontext_outer_class.proto\"\xd3\x01\n\x0eRequestContext\x12\x13\n\x0bsessionData\x18\x02 \x01(\x0c\x12\x14\n\x0clanguageCode\x18\x07 \x01(\t\x12\x12\n\nclientType\x18\x08 \x01(\x05\x12\x15\n\rclientVersion\x18\t \x01(\x03\x12=\n\rnativeContext\x18\n \x01(\x0b\x32&.ContextOuterClass.NativeClientContext\x12\x11\n\trequestId\x18\x0b \x01(\t\x12\x19\n\x11isPrefetchRequest\x18\r \x01(\x08\x42V\n:com.google.commerce.payments.orchestration.proto.ui.commonB\x18RequestContextOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_context_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n:com.google.commerce.payments.orchestration.proto.ui.commonB\030RequestContextOuterClass'
  _globals['_REQUESTCONTEXT']._serialized_start=91
  _globals['_REQUESTCONTEXT']._serialized_end=302
# @@protoc_insertion_point(module_scope)
