# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_context_outer_class.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"response_context_outer_class.proto\x12\x19ResponseContextOuterClass\"g\n\x0fResponseContext\x12\x1a\n\x12responseTimeMillis\x18\x01 \x01(\x03\x12\x13\n\x0bsessionData\x18\x02 \x01(\x0c\x12\x10\n\x08logToken\x18\x05 \x01(\x0c\x12\x11\n\trequestId\x18\x06 \x01(\tBW\n:com.google.commerce.payments.orchestration.proto.ui.commonB\x19ResponseContextOuterClass')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_context_outer_class_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n:com.google.commerce.payments.orchestration.proto.ui.commonB\031ResponseContextOuterClass'
  _globals['_RESPONSECONTEXT']._serialized_start=65
  _globals['_RESPONSECONTEXT']._serialized_end=168
# @@protoc_insertion_point(module_scope)
