# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restore.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrestore.proto\x12\x07Restore\x1a\x0c\x63ommon.proto\"[\n GetBackupDocumentChoicesResponse\x12\x37\n\x12\x62\x61\x63kupDocumentInfo\x18\x01 \x03(\x0b\x32\x1b.Restore.BackupDocumentInfo\"U\n\x1eGetBackupDeviceChoicesResponse\x12\x33\n\x10\x62\x61\x63kupDeviceInfo\x18\x01 \x03(\x0b\x32\x19.Restore.BackupDeviceInfo\"z\n\x10\x42\x61\x63kupDeviceInfo\x12\x11\n\tandroidId\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0crestoreToken\x18\x03 \x01(\t\x12\x14\n\x0cnumDocuments\x18\x04 \x01(\x05\x12\x19\n\x11lastCheckinTimeMs\x18\x05 \x01(\x03\"\x96\x01\n\x12\x42\x61\x63kupDocumentInfo\x12\x1c\n\x05\x64ocid\x18\x01 \x01(\x0b\x32\r.Common.Docid\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0bversionCode\x18\x03 \x01(\x05\x12%\n\x0ethumbnailImage\x18\x04 \x01(\x0b\x32\r.Common.Image\x12\x17\n\x0frestorePriority\x18\x05 \x01(\x05\x42+\n com.google.android.finsky.protosB\x07Restore')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\007Restore'
  _globals['_GETBACKUPDOCUMENTCHOICESRESPONSE']._serialized_start=40
  _globals['_GETBACKUPDOCUMENTCHOICESRESPONSE']._serialized_end=131
  _globals['_GETBACKUPDEVICECHOICESRESPONSE']._serialized_start=133
  _globals['_GETBACKUPDEVICECHOICESRESPONSE']._serialized_end=218
  _globals['_BACKUPDEVICEINFO']._serialized_start=220
  _globals['_BACKUPDEVICEINFO']._serialized_end=342
  _globals['_BACKUPDOCUMENTINFO']._serialized_start=345
  _globals['_BACKUPDOCUMENTINFO']._serialized_end=495
# @@protoc_insertion_point(module_scope)
