# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rev.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import document_v2_pb2 as document__v2__pb2
import doc_annotations_pb2 as doc__annotations__pb2
import tip_pb2 as tip__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trev.proto\x12\x03Rev\x1a\x11\x64ocument_v2.proto\x1a\x15\x64oc_annotations.proto\x1a\ttip.proto\x1a\x0c\x63ommon.proto\"\xe2\x01\n\x15\x43riticReviewsResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12)\n\x12\x61ggregateSentiment\x18\x02 \x01(\x0b\x32\r.Common.Image\x12\x17\n\x0ftotalNumReviews\x18\x03 \x01(\x05\x12\x18\n\x10percentFavorable\x18\x04 \x01(\x05\x12\x12\n\nsourceText\x18\x05 \x01(\t\x12$\n\x06source\x18\x06 \x01(\x0b\x32\x14.DocAnnotations.Link\x12\"\n\x06review\x18\x07 \x03(\x0b\x32\x12.DocumentV2.Review\"l\n\x12GetReviewsResponse\x12\"\n\x06review\x18\x01 \x03(\x0b\x32\x12.DocumentV2.Review\x12\x15\n\rmatchingCount\x18\x02 \x01(\x03\x12\x1b\n\x03tip\x18\x03 \x01(\x0b\x32\x0e.Tip.ReviewTip\"\xd5\x01\n\x0eReviewResponse\x12,\n\x0bgetResponse\x18\x01 \x01(\x0b\x32\x17.Rev.GetReviewsResponse\x12\x13\n\x0bnextPageUrl\x18\x02 \x01(\t\x12)\n\rupdatedReview\x18\x03 \x01(\x0b\x32\x12.DocumentV2.Review\x12\x1a\n\x12suggestionsListUrl\x18\x04 \x01(\t\x12\x39\n\x15\x63riticReviewsResponse\x18\x05 \x01(\x0b\x32\x1a.Rev.CriticReviewsResponseB\'\n com.google.android.finsky.protosB\x03Rev')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rev_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\003Rev'
  _globals['_CRITICREVIEWSRESPONSE']._serialized_start=86
  _globals['_CRITICREVIEWSRESPONSE']._serialized_end=312
  _globals['_GETREVIEWSRESPONSE']._serialized_start=314
  _globals['_GETREVIEWSRESPONSE']._serialized_end=422
  _globals['_REVIEWRESPONSE']._serialized_start=425
  _globals['_REVIEWRESPONSE']._serialized_end=638
# @@protoc_insertion_point(module_scope)
