# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: self_update.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11self_update.proto\x12\nSelfUpdate\"Y\n\x12SelfUpdateResponse\x12\"\n\x1arequiresUploadDeviceConfig\x18\x01 \x01(\x08\x12\x1f\n\x17latestClientVersionCode\x18\x02 \x01(\x05\x42.\n com.google.android.finsky.protosB\nSelfUpdate')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'self_update_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\nSelfUpdate'
  _globals['_SELFUPDATERESPONSE']._serialized_start=33
  _globals['_SELFUPDATERESPONSE']._serialized_end=122
# @@protoc_insertion_point(module_scope)
