# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: single_fop_payments_integrator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$single_fop_payments_integrator.proto\x12\x1bSingleFopPaymentsIntegrator\"R\n\"SingleFopPaymentsIntegratorContext\x12\x13\n\x0b\x63ommonToken\x18\x01 \x01(\x0c\x12\x17\n\x0finstrumentToken\x18\x02 \x01(\x0c\x42?\n com.google.android.finsky.protosB\x1bSingleFopPaymentsIntegrator')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'single_fop_payments_integrator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\033SingleFopPaymentsIntegrator'
  _globals['_SINGLEFOPPAYMENTSINTEGRATORCONTEXT']._serialized_start=69
  _globals['_SINGLEFOPPAYMENTSINTEGRATORCONTEXT']._serialized_end=151
# @@protoc_insertion_point(module_scope)
