# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload_device_config.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import device_configuration_proto_pb2 as device__configuration__proto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aupload_device_config.proto\x12\x12UploadDeviceConfig\x1a device_configuration_proto.proto\"=\n\x1aUploadDeviceConfigResponse\x12\x1f\n\x17uploadDeviceConfigToken\x18\x01 \x01(\t\"\x9d\x01\n\x19UploadDeviceConfigRequest\x12O\n\x13\x64\x65viceConfiguration\x18\x01 \x01(\x0b\x32\x32.DeviceConfigurationProto.DeviceConfigurationProto\x12\x14\n\x0cmanufacturer\x18\x02 \x01(\t\x12\x19\n\x11gcmRegistrationId\x18\x03 \x01(\tB6\n com.google.android.finsky.protosB\x12UploadDeviceConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_device_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.google.android.finsky.protosB\022UploadDeviceConfig'
  _globals['_UPLOADDEVICECONFIGRESPONSE']._serialized_start=84
  _globals['_UPLOADDEVICECONFIGRESPONSE']._serialized_end=145
  _globals['_UPLOADDEVICECONFIGREQUEST']._serialized_start=148
  _globals['_UPLOADDEVICECONFIGREQUEST']._serialized_end=305
# @@protoc_insertion_point(module_scope)
