# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/server/location/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@frameworks/proto_logging/stats/enums/server/location/enums.proto\x12\x17\x61ndroid.server.location*y\n\x14GpsSignalQualityEnum\x12\'\n\x1aGPS_SIGNAL_QUALITY_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1b\n\x17GPS_SIGNAL_QUALITY_POOR\x10\x00\x12\x1b\n\x17GPS_SIGNAL_QUALITY_GOOD\x10\x01*O\n\nGnssNiType\x12\t\n\x05VOICE\x10\x01\x12\r\n\tUMTS_SUPL\x10\x02\x12\x13\n\x0fUMTS_CTRL_PLANE\x10\x03\x12\x12\n\x0e\x45MERGENCY_SUPL\x10\x04*S\n\x14GnssUserResponseType\x12\x13\n\x0fRESPONSE_ACCEPT\x10\x01\x12\x11\n\rRESPONSE_DENY\x10\x02\x12\x13\n\x0fRESPONSE_NORESP\x10\x03*|\n\x12GnssNiEncodingType\x12\x0c\n\x08\x45NC_NONE\x10\x00\x12\x18\n\x14\x45NC_SUPL_GSM_DEFAULT\x10\x01\x12\x11\n\rENC_SUPL_UTF8\x10\x02\x12\x11\n\rENC_SUPL_UCS2\x10\x03\x12\x18\n\x0b\x45NC_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01*X\n\x10NfwProtocolStack\x12\x0e\n\nCTRL_PLANE\x10\x00\x12\x08\n\x04SUPL\x10\x01\x12\x07\n\x03IMS\x10\n\x12\x07\n\x03SIM\x10\x0b\x12\x18\n\x14OTHER_PROTOCOL_STACK\x10\x64*\x9d\x01\n\x0cNfwRequestor\x12\x0b\n\x07\x43\x41RRIER\x10\x00\x12\x07\n\x03OEM\x10\n\x12\x18\n\x14MODEM_CHIPSET_VENDOR\x10\x0b\x12\x17\n\x13GNSS_CHIPSET_VENDOR\x10\x0c\x12\x18\n\x14OTHER_CHIPSET_VENDOR\x10\r\x12\x15\n\x11\x41UTOMOBILE_CLIENT\x10\x14\x12\x13\n\x0fOTHER_REQUESTOR\x10\x64*b\n\x0fNfwResponseType\x12\x0c\n\x08REJECTED\x10\x00\x12!\n\x1d\x41\x43\x43\x45PTED_NO_LOCATION_PROVIDED\x10\x01\x12\x1e\n\x1a\x41\x43\x43\x45PTED_LOCATION_PROVIDED\x10\x02*\x1c\n\x08SuplMode\x12\x07\n\x03MSB\x10\x01\x12\x07\n\x03MSA\x10\x02*/\n\nLppProfile\x12\x0e\n\nUSER_PLANE\x10\x01\x12\x11\n\rCONTROL_PLANE\x10\x02*E\n\x12GlonassPosProtocol\x12\x0e\n\nRRC_CPLANE\x10\x01\x12\x0f\n\x0bRRLP_CPLANE\x10\x02\x12\x0e\n\nLPP_UPLANE\x10\x04*\x19\n\x07GpsLock\x12\x06\n\x02MO\x10\x01\x12\x06\n\x02NI\x10\x02\x42\x1c\x42\x18ServerLocationProtoEnumsP\x01')

_GPSSIGNALQUALITYENUM = DESCRIPTOR.enum_types_by_name['GpsSignalQualityEnum']
GpsSignalQualityEnum = enum_type_wrapper.EnumTypeWrapper(_GPSSIGNALQUALITYENUM)
_GNSSNITYPE = DESCRIPTOR.enum_types_by_name['GnssNiType']
GnssNiType = enum_type_wrapper.EnumTypeWrapper(_GNSSNITYPE)
_GNSSUSERRESPONSETYPE = DESCRIPTOR.enum_types_by_name['GnssUserResponseType']
GnssUserResponseType = enum_type_wrapper.EnumTypeWrapper(_GNSSUSERRESPONSETYPE)
_GNSSNIENCODINGTYPE = DESCRIPTOR.enum_types_by_name['GnssNiEncodingType']
GnssNiEncodingType = enum_type_wrapper.EnumTypeWrapper(_GNSSNIENCODINGTYPE)
_NFWPROTOCOLSTACK = DESCRIPTOR.enum_types_by_name['NfwProtocolStack']
NfwProtocolStack = enum_type_wrapper.EnumTypeWrapper(_NFWPROTOCOLSTACK)
_NFWREQUESTOR = DESCRIPTOR.enum_types_by_name['NfwRequestor']
NfwRequestor = enum_type_wrapper.EnumTypeWrapper(_NFWREQUESTOR)
_NFWRESPONSETYPE = DESCRIPTOR.enum_types_by_name['NfwResponseType']
NfwResponseType = enum_type_wrapper.EnumTypeWrapper(_NFWRESPONSETYPE)
_SUPLMODE = DESCRIPTOR.enum_types_by_name['SuplMode']
SuplMode = enum_type_wrapper.EnumTypeWrapper(_SUPLMODE)
_LPPPROFILE = DESCRIPTOR.enum_types_by_name['LppProfile']
LppProfile = enum_type_wrapper.EnumTypeWrapper(_LPPPROFILE)
_GLONASSPOSPROTOCOL = DESCRIPTOR.enum_types_by_name['GlonassPosProtocol']
GlonassPosProtocol = enum_type_wrapper.EnumTypeWrapper(_GLONASSPOSPROTOCOL)
_GPSLOCK = DESCRIPTOR.enum_types_by_name['GpsLock']
GpsLock = enum_type_wrapper.EnumTypeWrapper(_GPSLOCK)
GPS_SIGNAL_QUALITY_UNKNOWN = -1
GPS_SIGNAL_QUALITY_POOR = 0
GPS_SIGNAL_QUALITY_GOOD = 1
VOICE = 1
UMTS_SUPL = 2
UMTS_CTRL_PLANE = 3
EMERGENCY_SUPL = 4
RESPONSE_ACCEPT = 1
RESPONSE_DENY = 2
RESPONSE_NORESP = 3
ENC_NONE = 0
ENC_SUPL_GSM_DEFAULT = 1
ENC_SUPL_UTF8 = 2
ENC_SUPL_UCS2 = 3
ENC_UNKNOWN = -1
CTRL_PLANE = 0
SUPL = 1
IMS = 10
SIM = 11
OTHER_PROTOCOL_STACK = 100
CARRIER = 0
OEM = 10
MODEM_CHIPSET_VENDOR = 11
GNSS_CHIPSET_VENDOR = 12
OTHER_CHIPSET_VENDOR = 13
AUTOMOBILE_CLIENT = 20
OTHER_REQUESTOR = 100
REJECTED = 0
ACCEPTED_NO_LOCATION_PROVIDED = 1
ACCEPTED_LOCATION_PROVIDED = 2
MSB = 1
MSA = 2
USER_PLANE = 1
CONTROL_PLANE = 2
RRC_CPLANE = 1
RRLP_CPLANE = 2
LPP_UPLANE = 4
MO = 1
NI = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\030ServerLocationProtoEnumsP\001'
  _GPSSIGNALQUALITYENUM._serialized_start=93
  _GPSSIGNALQUALITYENUM._serialized_end=214
  _GNSSNITYPE._serialized_start=216
  _GNSSNITYPE._serialized_end=295
  _GNSSUSERRESPONSETYPE._serialized_start=297
  _GNSSUSERRESPONSETYPE._serialized_end=380
  _GNSSNIENCODINGTYPE._serialized_start=382
  _GNSSNIENCODINGTYPE._serialized_end=506
  _NFWPROTOCOLSTACK._serialized_start=508
  _NFWPROTOCOLSTACK._serialized_end=596
  _NFWREQUESTOR._serialized_start=599
  _NFWREQUESTOR._serialized_end=756
  _NFWRESPONSETYPE._serialized_start=758
  _NFWRESPONSETYPE._serialized_end=856
  _SUPLMODE._serialized_start=858
  _SUPLMODE._serialized_end=886
  _LPPPROFILE._serialized_start=888
  _LPPPROFILE._serialized_end=935
  _GLONASSPOSPROTOCOL._serialized_start=937
  _GLONASSPOSPROTOCOL._serialized_end=1006
  _GPSLOCK._serialized_start=1008
  _GPSLOCK._serialized_end=1033
# @@protoc_insertion_point(module_scope)
