# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/net/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4frameworks/proto_logging/stats/enums/net/enums.proto\x12\x0b\x61ndroid.net*\xab\x01\n\tTransport\x12\x16\n\x12TRANSPORT_CELLULAR\x10\x00\x12\x12\n\x0eTRANSPORT_WIFI\x10\x01\x12\x17\n\x13TRANSPORT_BLUETOOTH\x10\x02\x12\x16\n\x12TRANSPORT_ETHERNET\x10\x03\x12\x11\n\rTRANSPORT_VPN\x10\x04\x12\x18\n\x14TRANSPORT_WIFI_AWARE\x10\x05\x12\x14\n\x10TRANSPORT_LOWPAN\x10\x06\x42\x11\x42\rNetProtoEnumsP\x01')

_TRANSPORT = DESCRIPTOR.enum_types_by_name['Transport']
Transport = enum_type_wrapper.EnumTypeWrapper(_TRANSPORT)
TRANSPORT_CELLULAR = 0
TRANSPORT_WIFI = 1
TRANSPORT_BLUETOOTH = 2
TRANSPORT_ETHERNET = 3
TRANSPORT_VPN = 4
TRANSPORT_WIFI_AWARE = 5
TRANSPORT_LOWPAN = 6


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\rNetProtoEnumsP\001'
  _TRANSPORT._serialized_start=70
  _TRANSPORT._serialized_end=241
# @@protoc_insertion_point(module_scope)
