# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/view/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5frameworks/proto_logging/stats/enums/view/enums.proto\x12\x0c\x61ndroid.view*\xc6\x01\n\x10\x44isplayStateEnum\x12\x19\n\x15\x44ISPLAY_STATE_UNKNOWN\x10\x00\x12\x15\n\x11\x44ISPLAY_STATE_OFF\x10\x01\x12\x14\n\x10\x44ISPLAY_STATE_ON\x10\x02\x12\x16\n\x12\x44ISPLAY_STATE_DOZE\x10\x03\x12\x1e\n\x1a\x44ISPLAY_STATE_DOZE_SUSPEND\x10\x04\x12\x14\n\x10\x44ISPLAY_STATE_VR\x10\x05\x12\x1c\n\x18\x44ISPLAY_STATE_ON_SUSPEND\x10\x06*\xdc\x05\n\x12TransitionTypeEnum\x12\x10\n\x0cTRANSIT_NONE\x10\x00\x12\x1a\n\rTRANSIT_UNSET\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n\x15TRANSIT_ACTIVITY_OPEN\x10\x06\x12\x1a\n\x16TRANSIT_ACTIVITY_CLOSE\x10\x07\x12\x15\n\x11TRANSIT_TASK_OPEN\x10\x08\x12\x16\n\x12TRANSIT_TASK_CLOSE\x10\t\x12\x19\n\x15TRANSIT_TASK_TO_FRONT\x10\n\x12\x18\n\x14TRANSIT_TASK_TO_BACK\x10\x0b\x12\x1b\n\x17TRANSIT_WALLPAPER_CLOSE\x10\x0c\x12\x1a\n\x16TRANSIT_WALLPAPER_OPEN\x10\r\x12 \n\x1cTRANSIT_WALLPAPER_INTRA_OPEN\x10\x0e\x12!\n\x1dTRANSIT_WALLPAPER_INTRA_CLOSE\x10\x0f\x12\x1c\n\x18TRANSIT_TASK_OPEN_BEHIND\x10\x10\x12\x19\n\x15TRANSIT_TASK_IN_PLACE\x10\x11\x12\x1d\n\x19TRANSIT_ACTIVITY_RELAUNCH\x10\x12\x12&\n\x1eTRANSIT_DOCK_TASK_FROM_RECENTS\x10\x13\x1a\x02\x08\x01\x12\x1f\n\x1bTRANSIT_KEYGUARD_GOING_AWAY\x10\x14\x12,\n(TRANSIT_KEYGUARD_GOING_AWAY_ON_WALLPAPER\x10\x15\x12\x1c\n\x18TRANSIT_KEYGUARD_OCCLUDE\x10\x16\x12\x1e\n\x1aTRANSIT_KEYGUARD_UNOCCLUDE\x10\x17\x12%\n!TRANSIT_TRANSLUCENT_ACTIVITY_OPEN\x10\x18\x12&\n\"TRANSIT_TRANSLUCENT_ACTIVITY_CLOSE\x10\x19\x12#\n\x1fTRANSIT_CRASHING_ACTIVITY_CLOSE\x10\x1a\x42\x12\x42\x0eViewProtoEnumsP\x01')

_DISPLAYSTATEENUM = DESCRIPTOR.enum_types_by_name['DisplayStateEnum']
DisplayStateEnum = enum_type_wrapper.EnumTypeWrapper(_DISPLAYSTATEENUM)
_TRANSITIONTYPEENUM = DESCRIPTOR.enum_types_by_name['TransitionTypeEnum']
TransitionTypeEnum = enum_type_wrapper.EnumTypeWrapper(_TRANSITIONTYPEENUM)
DISPLAY_STATE_UNKNOWN = 0
DISPLAY_STATE_OFF = 1
DISPLAY_STATE_ON = 2
DISPLAY_STATE_DOZE = 3
DISPLAY_STATE_DOZE_SUSPEND = 4
DISPLAY_STATE_VR = 5
DISPLAY_STATE_ON_SUSPEND = 6
TRANSIT_NONE = 0
TRANSIT_UNSET = -1
TRANSIT_ACTIVITY_OPEN = 6
TRANSIT_ACTIVITY_CLOSE = 7
TRANSIT_TASK_OPEN = 8
TRANSIT_TASK_CLOSE = 9
TRANSIT_TASK_TO_FRONT = 10
TRANSIT_TASK_TO_BACK = 11
TRANSIT_WALLPAPER_CLOSE = 12
TRANSIT_WALLPAPER_OPEN = 13
TRANSIT_WALLPAPER_INTRA_OPEN = 14
TRANSIT_WALLPAPER_INTRA_CLOSE = 15
TRANSIT_TASK_OPEN_BEHIND = 16
TRANSIT_TASK_IN_PLACE = 17
TRANSIT_ACTIVITY_RELAUNCH = 18
TRANSIT_DOCK_TASK_FROM_RECENTS = 19
TRANSIT_KEYGUARD_GOING_AWAY = 20
TRANSIT_KEYGUARD_GOING_AWAY_ON_WALLPAPER = 21
TRANSIT_KEYGUARD_OCCLUDE = 22
TRANSIT_KEYGUARD_UNOCCLUDE = 23
TRANSIT_TRANSLUCENT_ACTIVITY_OPEN = 24
TRANSIT_TRANSLUCENT_ACTIVITY_CLOSE = 25
TRANSIT_CRASHING_ACTIVITY_CLOSE = 26


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\016ViewProtoEnumsP\001'
  _TRANSITIONTYPEENUM.values_by_name["TRANSIT_DOCK_TASK_FROM_RECENTS"]._options = None
  _TRANSITIONTYPEENUM.values_by_name["TRANSIT_DOCK_TASK_FROM_RECENTS"]._serialized_options = b'\010\001'
  _DISPLAYSTATEENUM._serialized_start=72
  _DISPLAYSTATEENUM._serialized_end=270
  _TRANSITIONTYPEENUM._serialized_start=273
  _TRANSITIONTYPEENUM._serialized_end=1005
# @@protoc_insertion_point(module_scope)
