# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/sysui/notification_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIframeworks/proto_logging/stats/enums/stats/sysui/notification_enums.proto\x12\x13\x61ndroid.stats.sysui*\xce\x01\n\x16NotificationImportance\x12#\n\x16IMPORTANCE_UNSPECIFIED\x10\x98\xf8\xff\xff\xff\xff\xff\xff\xff\x01\x12\x13\n\x0fIMPORTANCE_NONE\x10\x00\x12\x12\n\x0eIMPORTANCE_MIN\x10\x01\x12\x12\n\x0eIMPORTANCE_LOW\x10\x02\x12\x16\n\x12IMPORTANCE_DEFAULT\x10\x03\x12\x13\n\x0fIMPORTANCE_HIGH\x10\x04\x12%\n!IMPORTANCE_IMPORTANT_CONVERSATION\x10\x05')

_NOTIFICATIONIMPORTANCE = DESCRIPTOR.enum_types_by_name['NotificationImportance']
NotificationImportance = enum_type_wrapper.EnumTypeWrapper(_NOTIFICATIONIMPORTANCE)
IMPORTANCE_UNSPECIFIED = -1000
IMPORTANCE_NONE = 0
IMPORTANCE_MIN = 1
IMPORTANCE_LOW = 2
IMPORTANCE_DEFAULT = 3
IMPORTANCE_HIGH = 4
IMPORTANCE_IMPORTANT_CONVERSATION = 5


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFICATIONIMPORTANCE._serialized_start=99
  _NOTIFICATIONIMPORTANCE._serialized_end=305
# @@protoc_insertion_point(module_scope)
