# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/storage/storage_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFframeworks/proto_logging/stats/enums/stats/storage/storage_enums.proto\x12\x15\x61ndroid.stats.storage*C\n\x13\x45xternalStorageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SD_CARD\x10\x01\x12\x07\n\x03USB\x10\x02\x12\t\n\x05OTHER\x10\x03')

_EXTERNALSTORAGETYPE = DESCRIPTOR.enum_types_by_name['ExternalStorageType']
ExternalStorageType = enum_type_wrapper.EnumTypeWrapper(_EXTERNALSTORAGETYPE)
UNKNOWN = 0
SD_CARD = 1
USB = 2
OTHER = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTERNALSTORAGETYPE._serialized_start=97
  _EXTERNALSTORAGETYPE._serialized_end=164
# @@protoc_insertion_point(module_scope)
