# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/hardware/sensor/assist/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGframeworks/proto_logging/stats/enums/hardware/sensor/assist/enums.proto\x12\x1e\x61ndroid.hardware.sensor.assist*\xa1\x01\n\x16\x41ssistGestureStageEnum\x12 \n\x1c\x41SSIST_GESTURE_STAGE_UNKNOWN\x10\x00\x12!\n\x1d\x41SSIST_GESTURE_STAGE_PROGRESS\x10\x01\x12\x1f\n\x1b\x41SSIST_GESTURE_STAGE_PRIMED\x10\x02\x12!\n\x1d\x41SSIST_GESTURE_STAGE_DETECTED\x10\x03*\x88\x01\n\x19\x41ssistGestureFeedbackEnum\x12#\n\x1f\x41SSIST_GESTURE_FEEDBACK_UNKNOWN\x10\x00\x12$\n ASSIST_GESTURE_FEEDBACK_NOT_USED\x10\x01\x12 \n\x1c\x41SSIST_GESTURE_FEEDBACK_USED\x10\x02\x42\x1b\x42\x17\x41ssistGestureProtoEnumsP\x01')

_ASSISTGESTURESTAGEENUM = DESCRIPTOR.enum_types_by_name['AssistGestureStageEnum']
AssistGestureStageEnum = enum_type_wrapper.EnumTypeWrapper(_ASSISTGESTURESTAGEENUM)
_ASSISTGESTUREFEEDBACKENUM = DESCRIPTOR.enum_types_by_name['AssistGestureFeedbackEnum']
AssistGestureFeedbackEnum = enum_type_wrapper.EnumTypeWrapper(_ASSISTGESTUREFEEDBACKENUM)
ASSIST_GESTURE_STAGE_UNKNOWN = 0
ASSIST_GESTURE_STAGE_PROGRESS = 1
ASSIST_GESTURE_STAGE_PRIMED = 2
ASSIST_GESTURE_STAGE_DETECTED = 3
ASSIST_GESTURE_FEEDBACK_UNKNOWN = 0
ASSIST_GESTURE_FEEDBACK_NOT_USED = 1
ASSIST_GESTURE_FEEDBACK_USED = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\027AssistGestureProtoEnumsP\001'
  _ASSISTGESTURESTAGEENUM._serialized_start=108
  _ASSISTGESTURESTAGEENUM._serialized_end=269
  _ASSISTGESTUREFEEDBACKENUM._serialized_start=272
  _ASSISTGESTUREFEEDBACKENUM._serialized_end=408
# @@protoc_insertion_point(module_scope)
