# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/stats/accessibility/accessibility_enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRframeworks/proto_logging/stats/enums/stats/accessibility/accessibility_enums.proto\x12\x1b\x61ndroid.stats.accessibility*\x85\x01\n\x0cShortcutType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x0f\n\x0b\x41\x31\x31Y_BUTTON\x10\x01\x12\x0e\n\nVOLUME_KEY\x10\x02\x12\x0e\n\nTRIPLE_TAP\x10\x03\x12\x1a\n\x16\x41\x31\x31Y_BUTTON_LONG_PRESS\x10\x04\x12\x16\n\x12\x41\x31\x31Y_FLOATING_MENU\x10\x05*7\n\rServiceStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x0c\n\x08\x44ISABLED\x10\x02*\x83\x01\n\x11MagnificationMode\x12\x1e\n\x1aMAGNIFICATION_UNKNOWN_MODE\x10\x00\x12\x1d\n\x19MAGNIFICATION_FULL_SCREEN\x10\x01\x12\x18\n\x14MAGNIFICATION_WINDOW\x10\x02\x12\x15\n\x11MAGNIFICATION_ALL\x10\x03\x42\x02P\x01')

_SHORTCUTTYPE = DESCRIPTOR.enum_types_by_name['ShortcutType']
ShortcutType = enum_type_wrapper.EnumTypeWrapper(_SHORTCUTTYPE)
_SERVICESTATUS = DESCRIPTOR.enum_types_by_name['ServiceStatus']
ServiceStatus = enum_type_wrapper.EnumTypeWrapper(_SERVICESTATUS)
_MAGNIFICATIONMODE = DESCRIPTOR.enum_types_by_name['MagnificationMode']
MagnificationMode = enum_type_wrapper.EnumTypeWrapper(_MAGNIFICATIONMODE)
UNKNOWN_TYPE = 0
A11Y_BUTTON = 1
VOLUME_KEY = 2
TRIPLE_TAP = 3
A11Y_BUTTON_LONG_PRESS = 4
A11Y_FLOATING_MENU = 5
UNKNOWN = 0
ENABLED = 1
DISABLED = 2
MAGNIFICATION_UNKNOWN_MODE = 0
MAGNIFICATION_FULL_SCREEN = 1
MAGNIFICATION_WINDOW = 2
MAGNIFICATION_ALL = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _SHORTCUTTYPE._serialized_start=116
  _SHORTCUTTYPE._serialized_end=249
  _SERVICESTATUS._serialized_start=251
  _SERVICESTATUS._serialized_end=306
  _MAGNIFICATIONMODE._serialized_start=309
  _MAGNIFICATIONMODE._serialized_end=440
# @@protoc_insertion_point(module_scope)
