# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/bluetooth/hfp/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>frameworks/proto_logging/stats/enums/bluetooth/hfp/enums.proto\x12\x15\x61ndroid.bluetooth.hfp*I\n\x08ScoCodec\x12\x15\n\x11SCO_CODEC_UNKNOWN\x10\x00\x12\x12\n\x0eSCO_CODEC_CVSD\x10\x01\x12\x12\n\x0eSCO_CODEC_MSBC\x10\x02\x42\x1a\x42\x16\x42luetoothHfpProtoEnumsP\x01')

_SCOCODEC = DESCRIPTOR.enum_types_by_name['ScoCodec']
ScoCodec = enum_type_wrapper.EnumTypeWrapper(_SCOCODEC)
SCO_CODEC_UNKNOWN = 0
SCO_CODEC_CVSD = 1
SCO_CODEC_MSBC = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\026BluetoothHfpProtoEnumsP\001'
  _SCOCODEC._serialized_start=89
  _SCOCODEC._serialized_end=162
# @@protoc_insertion_point(module_scope)
