# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frameworks/proto_logging/stats/enums/telecomm/enums.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9frameworks/proto_logging/stats/enums/telecomm/enums.proto\x12\x0f\x61ndroid.telecom*\xef\x01\n\rCallStateEnum\x12\x07\n\x03NEW\x10\x00\x12\x0e\n\nCONNECTING\x10\x01\x12\x18\n\x14SELECT_PHONE_ACCOUNT\x10\x02\x12\x0b\n\x07\x44IALING\x10\x03\x12\x0b\n\x07RINGING\x10\x04\x12\n\n\x06\x41\x43TIVE\x10\x05\x12\x0b\n\x07ON_HOLD\x10\x06\x12\x10\n\x0c\x44ISCONNECTED\x10\x07\x12\x0b\n\x07\x41\x42ORTED\x10\x08\x12\x11\n\rDISCONNECTING\x10\t\x12\x0b\n\x07PULLING\x10\n\x12\x0c\n\x08\x41NSWERED\x10\x0b\x12\x14\n\x10\x41UDIO_PROCESSING\x10\x0c\x12\x15\n\x11SIMULATED_RINGING\x10\r*\xe0\x01\n\x13\x44isconnectCauseEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\t\n\x05LOCAL\x10\x02\x12\n\n\x06REMOTE\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04\x12\n\n\x06MISSED\x10\x05\x12\x0c\n\x08REJECTED\x10\x06\x12\x08\n\x04\x42USY\x10\x07\x12\x0e\n\nRESTRICTED\x10\x08\x12\t\n\x05OTHER\x10\t\x12$\n CONNECTION_MANAGER_NOT_SUPPORTED\x10\n\x12\x16\n\x12\x41NSWERED_ELSEWHERE\x10\x0b\x12\x0f\n\x0b\x43\x41LL_PULLED\x10\x0c\x42\x15\x42\x11TelecomProtoEnumsP\x01')

_CALLSTATEENUM = DESCRIPTOR.enum_types_by_name['CallStateEnum']
CallStateEnum = enum_type_wrapper.EnumTypeWrapper(_CALLSTATEENUM)
_DISCONNECTCAUSEENUM = DESCRIPTOR.enum_types_by_name['DisconnectCauseEnum']
DisconnectCauseEnum = enum_type_wrapper.EnumTypeWrapper(_DISCONNECTCAUSEENUM)
NEW = 0
CONNECTING = 1
SELECT_PHONE_ACCOUNT = 2
DIALING = 3
RINGING = 4
ACTIVE = 5
ON_HOLD = 6
DISCONNECTED = 7
ABORTED = 8
DISCONNECTING = 9
PULLING = 10
ANSWERED = 11
AUDIO_PROCESSING = 12
SIMULATED_RINGING = 13
UNKNOWN = 0
ERROR = 1
LOCAL = 2
REMOTE = 3
CANCELED = 4
MISSED = 5
REJECTED = 6
BUSY = 7
RESTRICTED = 8
OTHER = 9
CONNECTION_MANAGER_NOT_SUPPORTED = 10
ANSWERED_ELSEWHERE = 11
CALL_PULLED = 12


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\021TelecomProtoEnumsP\001'
  _CALLSTATEENUM._serialized_start=79
  _CALLSTATEENUM._serialized_end=318
  _DISCONNECTCAUSEENUM._serialized_start=321
  _DISCONNECTCAUSEENUM._serialized_end=545
# @@protoc_insertion_point(module_scope)
